export const quotes = [
    "A mind is like a parachute. It doesn't work if it isn't open.",
    "That which does not kill us makes us stronger.",
    "Remember no one can make you feel inferior without your consent.",
    "Your worth consists in what you are and not in what you have.",
    "Be yourself; everyone else is already taken.",
    "This above all: to thine own self be true.",
    "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind.",
    "Two roads divergd in a wood, and I-I took the one less traveled by, And that has made all the difference.",
    "We must not allow other people's limited perceptions to define us.",
    "Be a first rate version of yourself, not a second rate version of someone else.",
    "If I am not for myself, who is for me? And if I am only for myself, what am I? And if not now, when?",
    "What you do speaks so loudly that I cannot hear what you say.",
    "The only true wisdom is knowing that you know nothing.",
    "Wise men speak because they have something to say; fools because they have to say something.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "There are two was of spreading light: to be the candle or the mirror that reflects it.",
    "In this world nothing can be said to be certain, except death and taxes.",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    "Music in the soul can be heard by the universe.",
    "If you tell the truth, you don't have to remember anything.",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    "If you cannot do great things, do small things in a great way.",
    "Too many of us are not living our dreams because we are living our fears.",
    "He who angers you conquers you.",
    "The difference between ordinary and extraordinary is that little extra.",
    "The secret of business is to know something that nobody else knows.",
    "Anyone who stops learning is old, whether at 20 or 80. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young."
]

export const authors = [
    "Frank Zappa",
    "Friedrich Nietzsche",
    "Eleanor Roosevelt",
    "Thomas Edison",
    "Oscar Wilde",
    "William Shakespeare",
    "Bernard M. Baruch",
    "Robert Frost",
    "Virginia Satir",
    "Judy Garland",
    "Robbi Hillel",
    "Ralph Waldo Emerson",
    "Socrates",
    "Plato",
    "Eleanor Roosevelt",
    "Edith Wharton",
    "Benjamin Franklin",
    "Mark Twain",
    "Lao Tzu",
    "Mark Twain",
    "Oprah Winfrey",
    "Napoleon Hill",
    "Les Brown",
    "Elizabeth Kenny",
    "Jimmy Johnson",
    "Aristotle Onassis",
    "Henry Ford"
]